version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  ratelimiter-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis